// <auto-generated />
using System;
using JaizBank.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JaizBank.Data.Migrations
{
    [DbContext(typeof(TransactionsContext))]
    [Migration("20220912222308_Added")]
    partial class Added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JaizBank.Entities.JaizBankModel.Transactions", b =>
                {
                    b.Property<int>("TransactionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionsId"), 1L, 1);

                    b.Property<string>("AID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accelerex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<double?>("AuthorizationCode")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebitCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Offline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PTAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("int");

                    b.Property<string>("Stan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionsId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionsId = 1,
                            AID = "A0000000041010",
                            Accelerex = "2.0.0-090921-LINT",
                            Amount = 0.01,
                            AuthorizationCode = 0.0,
                            DateTime = new DateTime(2022, 8, 30, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            DebitCardNo = "539941******3369",
                            ExpireDate = new DateTime(2022, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "NO, 174 NTA/MBUORA RD, PORTHARCOURT",
                            MerchantName = "LIZPEE GLOBAL RESOURCES",
                            Offline = "CVM",
                            PTAD = "Global Accelerex",
                            RRN = "000210002450",
                            ResponseCode = 91,
                            Stan = "003862",
                            TerminalId = "23011845"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
